# Generated by Django 4.1.3 on 2022-11-16 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=10000)),
                ('path', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'adresses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('type', models.CharField(max_length=50)),
                ('signature', models.BooleanField()),
                ('size', models.FloatField()),
            ],
            options={
                'db_table': 'documents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('postAdress', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlockhainDocumentor.adress')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlockhainDocumentor.document')),
            ],
            options={
                'db_table': 'blockchain',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='adress',
            name='fileName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlockhainDocumentor.document'),
        ),
    ]
