# Generated by Django 4.1.3 on 2022-11-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlockhainDocumentor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='postAdress',
            new_name='email',
        ),
    ]
