# Generated by Django 4.1.3 on 2022-11-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlockhainDocumentor', '0002_rename_postadress_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='username',
        ),
    ]
