# Generated by Django 4.1.3 on 2022-12-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlockhainDocumentor', '0004_delete_user_document_docfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'managed': True, 'verbose_name_plural': 'Документы'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
        migrations.AlterField(
            model_name='document',
            name='docFile',
            field=models.FileField(default=None, upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=10000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='document',
            name='signature',
            field=models.BooleanField(verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='document',
            name='size',
            field=models.FloatField(verbose_name='Размер'),
        ),
    ]
