# Generated by Django 4.1.3 on 2022-12-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlockhainDocumentor', '0006_alter_document_docfile_alter_document_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='size',
        ),
    ]
