# Generated by Django 4.1.3 on 2022-12-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlockhainDocumentor', '0007_remove_document_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.CharField(default=1, max_length=10, verbose_name='Размер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='docFile',
            field=models.FileField(default=None, upload_to='', verbose_name='Файл'),
        ),
    ]
