# Generated by Django 4.1.3 on 2023-04-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlockhainDocumentor', '0008_document_size_alter_document_docfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AddField(
            model_name='document',
            name='own',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterModelTable(
            name='document',
            table=None,
        ),
    ]
