# Generated by Django 4.1.3 on 2023-04-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlockhainDocumentor', '0009_alter_document_options_document_own_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'managed': True, 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelTable(
            name='document',
            table='documents',
        ),
    ]
