# Generated by Django 4.2 on 2023-05-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlockhainDocumentor', '0011_alter_document_own'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(default='отправлен в росздрав', max_length=16, verbose_name='Размер'),
        ),
    ]
