# Generated by Django 4.2 on 2023-05-16 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlockhainDocumentor', '0012_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
