# Generated by Django 4.2 on 2023-05-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlockhainDocumentor', '0013_document_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='order_date',
            new_name='date',
        ),
    ]
