# Generated by Django 4.2 on 2023-05-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlockhainDocumentor', '0014_rename_order_date_document_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
